name: Kirim Jadwal Otomatis
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python main.py
